### ISSUE TITLE
Teardown/cleanup logic is sometimes not called.

### ISSUE THREAD

**Issue by ghost** [fafhrd91/aiohttp#7986]
### Describe the bug

For both setup-teardown mechanisms provided by aiohttp, 'cleanup_ctx' and 'on_startup/on_cleanup', the teardown is sometimes not called. Even when kept in a finally block.

### To Reproduce

This is a simple order processing example.
We have an endpoint ```'/order'``` that a client can use to place an order.
The CTX_TYPE determines which setup-teardown mechanism is used. Possible values, '' and 'ctx'.
The application behaves okay when there are no orders in the queue, but when there are, the teardown logic is never called.

main.py holds the server code, an endpoint, an app factory and flipping the type of setup-teardown used.
```python
# main.py
from aiohttp import web
import processor  # Import our processor plugin

CTX_TYPE = '' # Contol which type of setup-teardown is used. ctx/seted

async def process_order(req: web.Request):
    queue = req.app[processor.QUEUE]
    task = next(processor.GENERATOR)  # Get a task
    await queue.put(task)  # Add task to be processed
    return web.Response(body=f"Order placed: {task}")


routes = [web.get("/order", process_order)]


async def application():
    app = web.Application()
    processor.setup(app, CTX_TYPE)  # Install plugin
    app.add_routes(routes)
    return app


if __name__ == "__main__":
    try:
        web.run_app(application())
        # Remember to press Ctrl+C to stop the application
        # when there are some tasks on queue to see the effect
        # of chosen setup-teardown.
    except KeyboardInterrupt:
        ...
```

processor.py is simply a plugin that is meant to process incomming orders through a simple processor function, there are the two implementations of setup-teardown used, one is set when installing the plugin.
```python
# processor.py
from aiohttp import web
import asyncio

QUEUE = "task_queue.app"
TASKS = "tasks_list.app"


# Infinite Task Generator
def tasks_generator(start: int = 1):
    while True:
        yield f"Task_{start}"
        start += 1


# Dummy infinite task generator.
GENERATOR = tasks_generator()


# For processing the incomming tasks in the Queue
async def processor(processor_id: int, tasks_queue: asyncio.Queue):
    print(f"Worker {processor_id}: Up and Running.")
    try:
        while True:
            task = await tasks_queue.get()
            print(f"Worker {processor_id}: Processing {task}.")
            await asyncio.sleep(2)  # Emulate some heavy processing.
            print(f'  Processed {task}.')
    except asyncio.CancelledError:
        print(f"Worker {processor_id}: Killed.")
    finally:
        print(f"Worker {processor_id}: Shutting down.")


# The processors lifetime is setup and destroyed here.
async def processor_ctx(app: web.Application):
    print("[plugin]: Starting processors.")
    queue = asyncio.Queue(5) # Only store 5 tasks at a time
    workers = [asyncio.create_task(processor(pid, queue)) for pid in range(1, 4)]
    app[QUEUE] = queue
    yield
    print("[plugin]: Stoping processors.")
    [w.cancel() for w in workers]
    await asyncio.gather(*workers)


# Create the processors and save in the background
async def processor_setup(app: web.Application):
    print("[plugin]: Starting processors.")
    queue = asyncio.Queue(5)
    workers = [asyncio.create_task(processor(pid, queue)) for pid in range(1, 4)]
    app[QUEUE] = queue
    app[TASKS] = workers


# Destroy the saved processors from above
async def processor_teardown(app: web.Application):
    print("[plugin]: Stoping processors.")
    workers = app[TASKS]
    [w.cancel() for w in workers]
    await asyncio.gather(*workers)


# To connect our plugin to out application.
def setup(app: web.Application, toggle: str = ""):
    """Control which setup-teardown to use using the toggle parameter"""
    if toggle == "ctx":
        app.cleanup_ctx.append(processor_ctx)
    else:
        app.on_startup.append(processor_setup)
        app.on_cleanup.append(processor_teardown)
```

stress.py - just a simple stressor, nothing important here.
```python
# stress.py
from aiohttp import ClientSession, ServerDisconnectedError
import asyncio

HOST = "localhost"  # Default aiohttp server host
PORT = 8080  # Default aiohttp server port
BASE_URL = f"http://{HOST}:{PORT}"


async def place_order(session: ClientSession):
    async with session.get("/order") as resp:
        print(await resp.text())


async def stress():
    async with ClientSession(BASE_URL) as session:
        orders = (place_order(session) for _ in range(100))
        await asyncio.gather(*orders)


if __name__ == "__main__":
    try:
        asyncio.run(stress())
    except: ... 
```

To get the expected output.

1. Start the application by running
```bash
$ python3 main.py
```
then press ctrl-c, this will stop the program and the teardown logic will run properly.
Restart the application again.

2. Start the stressor.
```bash
$ python3 stress.py
```
Press ctrl-c on the server terminal before all the orders finish processing, don't mind the stressor errors. Here you will see the teardown logic not performed, it just shuts down.

3. Set the CTX_TOGGLE variable in main.py from ```''``` to ```'ctx'``` to activate the other setup-teardown mechanism then redo the above steps.

I am not sure if it's an aiohttp issue or python's since the finally block in the processor is not even called.

### Expected behavior

[plugin]: Starting processors.
Worker 1: Up and Running.
Worker 2: Up and Running.
Worker 3: Up and Running.
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Worker 1: Processing Task_1.
Worker 2: Processing Task_2.
Worker 3: Processing Task_3.
  Processed Task_1.
Worker 1: Processing Task_4.
  Processed Task_2.
Worker 2: Processing Task_5.
  Processed Task_3.
Worker 3: Processing Task_6.
^C[plugin]: Stoping processors.
Worker 1: Killed.
Worker 1: Shutting down.
Worker 2: Killed.
Worker 2: Shutting down.
Worker 3: Killed.
Worker 3: Shutting down.

### Logs/tracebacks

```python-traceback
[plugin]: Starting processors.
Worker 1: Up and Running.
Worker 2: Up and Running.
Worker 3: Up and Running.
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Worker 1: Processing Task_1.
Worker 2: Processing Task_2.
Worker 3: Processing Task_3.
  Processed Task_1.
Worker 1: Processing Task_4.
  Processed Task_2.
Worker 2: Processing Task_5.
  Processed Task_3.
Worker 3: Processing Task_6.
```

### Python Version

```console
Python 3.11.6
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.9.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Requires: aiosignal, attrs, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.9.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Arch Linux

### Related component

Server

### Code of Conduct

- [ ] I agree to follow the aio-libs Code of Conduct

**Comment by thee-dushbag** [comment]
Gunicorn shutdown procedure seems to eventually initiate cleanup very well. I guess its an issue with the web.run_app

**Comment by thee-dushbag** [comment]
@Dreamsorcerer
I think it's an issue with the internal aiohttp server (web.run_app) I believe, it doesn't handle shutdown correctly by failing to run cleanup sometimes. As for my reproducer, sorry for the length but most of it is just setting an environment to reproduce the issue.

Below is a shorter reproducer, if you focus on the section surrounded by the long line comments, you can use `wrk` to stress the app on `http://localhost:8080` around 100 connections.

I've implemented three possible ways to initiate setup-teardown by passing one of `(ctx, seted, none)` as the first argument when starting the server.

Steps:
- Start the server with `python3 main.py [ctx|seted|none]`
- Stop it, it should see the setup and shutdown logic called
- Start again
- Smash it with wrk, a few connections like 20 should do it
- Stop the server, the cleanup is not called
- Start the server again with a different choice.

```bash
wrk -c 20 http://localhost:8080
```

```python
# main.py
from itertools import count
from aiohttp import web
import asyncio

QUEUE, TASK = "QUEUE", "TASK"


# -------------------------------------------------------------------------------------


# Create the worker and save in the background
async def worker_setup(app: web.Application):
    print("[plugin]: Starting worker.")
    app[QUEUE] = asyncio.Queue(3)  # Only store 3 tasks at a time
    app[TASK] = asyncio.create_task(worker(app[QUEUE]))


# Destroy the saved worker from above
async def worker_teardown(app: web.Application):
    print("[plugin]: Stopping worker.")
    await app[QUEUE].join()
    app[TASK].cancel()
    await app[TASK]


async def worker_seted(app: web.Application):
    await worker_setup(app)
    yield
    await worker_teardown(app)


async def worker_ctx(app: web.Application):
    async with SimpleCTX(app, worker_setup, worker_teardown):
        yield


# Connect the plugin to our application.
def installer(app: web.Application):
    """Control which setup-teardown using the argv[1] passed in"""
    from sys import argv
    CTX_TYPE = argv[1] if len(argv) > 2 else ""

    if CTX_TYPE == "seted":
        app.cleanup_ctx.append(worker_seted)
    elif CTX_TYPE == "ctx":
        app.cleanup_ctx.append(worker_ctx)
    else:
        app.on_startup.append(worker_setup)
        app.on_cleanup.append(worker_teardown)


async def worker(tasks_queue: asyncio.Queue):
    print(f"Worker: Up and Running.")
    try:
        await workon(tasks_queue)
    except asyncio.CancelledError:
        print(f"Worker: Killed.")
    finally:
        print(f"Worker: Shutting down.")


# -------------------------------------------------------------------------------------


class SimpleCTX:
    def __init__(self, app, enter, exit) -> None:
        self.app = app
        self.enter = enter
        self.exit = exit

    async def __aenter__(self):
        await self.enter(self.app)

    async def __aexit__(self, *errs):
        await self.exit(self.app)


# Actual processing
async def workon(queue: asyncio.Queue):
    while True:
        task = await queue.get()
        print(f"Worker: Processing Task {task}.")
        await asyncio.sleep(0.5)  # Simulate some heavy processing.
        queue.task_done()


# Task Generator
GENERATOR = count(1)


async def enqueue_task(req: web.Request):
    queue = req.app[QUEUE]
    await queue.put(next(GENERATOR))  # Add task to be processed
    return web.Response()


app = web.Application()
installer(app)
app.router.add_get("/", enqueue_task)

try:
    web.run_app(app)
except KeyboardInterrupt:
    ...
```

Cleanup is called when the task queue is empty else it is not called.

**Comment by Dreamsorcerer** [comment]
Some things you've mentioned about queues and workloads suggests to me that you may have created some background tasks which aiohttp will try to wait on (for a minute or so if they don't complete).
See: https://docs.aiohttp.org/en/stable/web_advanced.html#graceful-shutdown

If that's not helped, I'll try and test it tomorrow.

**Comment by thee-dushbag** [comment]
The application shuts down gracefully, the problem is python does not execute the finally block in the `worker` function or the `__aexit__` in `SimpleCTX`, aiohttp cleanup also doesn't call the cleanup passed to it on `on_cleanup`.

As for the queued tasks, I've set them in such a way they all get executed before shutting down since they can only be three in the queue. Therefore ensuring a graceful shutdown for my part.

I think it's somewhat a bug in `python/asyncio`, maybe the addition of `async/await` broke python's cleanup (i.e. call `__exit__` for each `__enter__`, execute finally blocks, ...), some type of race condition.

Just try it for yourself to see what I mean.

Thanks for your time, I appreciate your effort.

**Comment by Dreamsorcerer** [comment]
> The application shuts down gracefully, the problem is python does not execute the finally block in the `worker` function or the `__aexit__` in `SimpleCTX`, aiohttp cleanup also doesn't call the cleanup passed to it on `on_cleanup`.

I'm still not entirely clear on the reproducer. If it doesn't run cleanup at all, then why such a complex reproducer, surely this would reproduce your problem?

```
async def foo(app):
    print("STARTUP")
    yield
    print("SHUTDOWN")

app = web.Application()
app.cleanup_ctx.append(foo)
web.run_app(app)
```

If I do run run your latest example and then close the application, it works as expected:
```
> python3 test.py
[plugin]: Starting worker.
Worker: Up and Running.
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^C
[plugin]: Stopping worker.
Worker: Killed.
Worker: Shutting down.
```

Even when loading it with `wrk` as suggested, it works correctly (though the handlers are so slow, it takes about 30 seconds to complete):
```
$ python3 test.py
[plugin]: Starting worker.
Worker: Up and Running.
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
Worker: Processing Task 1.
Worker: Processing Task 2.
Worker: Processing Task 3.
Worker: Processing Task 4.
Worker: Processing Task 5.
Worker: Processing Task 6.
^CWorker: Processing Task 7.
Worker: Processing Task 8.
Worker: Processing Task 9.
Worker: Processing Task 10.
Worker: Processing Task 11.
Worker: Processing Task 12.
Worker: Processing Task 13.
Worker: Processing Task 14.
Worker: Processing Task 15.
Worker: Processing Task 16.
Worker: Processing Task 17.
Worker: Processing Task 18.
Worker: Processing Task 19.
Worker: Processing Task 20.
Worker: Processing Task 21.
Worker: Processing Task 22.
Worker: Processing Task 23.
Worker: Processing Task 24.
Worker: Processing Task 25.
Worker: Processing Task 26.
[plugin]: Stopping worker.
Worker: Processing Task 27.
Worker: Processing Task 28.
Worker: Processing Task 29.
Worker: Killed.
Worker: Shutting down.
```

**Comment by Dreamsorcerer** [comment]
In the logs/traceback section of your original post, the terminal output doesn't even have `^C`, which suggests you haven't even done Ctrl+C at that point. Are you sure you're not just killing the process or something?

**Comment by thee-dushbag** [comment]
This is what I get on my side.

![py3-empty](https://github.com/aio-libs/aiohttp/assets/112253408/bd9498a1-a886-4f0f-ad60-9056796ab0cd)

After starting `wrk` in another terminal.

![py3-full](https://github.com/aio-libs/aiohttp/assets/112253408/623e8710-9f13-46a3-89a9-250447254891)

I am lost, for sure. For now I will close the issue, let me do a deep dive into my configurations or something, check the arch updates.
This has never happened before though.

**Comment by Dreamsorcerer** [comment]
As a start, I'd suggest adding a print at the end of the script:
```
try:
    web.run_app(app)
except:
    print("FINISHED")
    raise
```

If that doesn't print, then I still suspect the process is getting killed for some reason. If it does print, and the exception is not a KeyboardInterrupt, then that could suggest another problem. If it is a KeyboardInterrupt, then maybe there is something going wrong within aiohttp or asyncio.

**Comment by thee-dushbag** [comment]
Yep, the process is definately getting killed somehow by something.
Must be a configuration issue, service, whatever, idk.
Sorry for this waste of your time.
Thank you for your help.
